import type { Metadata } from "next";
import { Lora, Poppins } from 'next/font/google';
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["800"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Ugyen Wangda Gyeltshen",
  description: "Generated by Ugyen Wangda Gyeltshen",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head><link rel="icon" href="/favicon.ico" /></head>
        <body className={`${poppins.variable} ${lora.variable}`}>
        {children}
      </body>
    </html>
  );
}
